import { IProjectStatusUpdate } from "./interfaces/project-status-update.interface";

export const data_09_01_2023: IProjectStatusUpdate[] = [
    {
      projectId: "1",
      projectName: "FEMA CIS",
      programName: "FEMA",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Green",
      escalationMetricStatus: "Yellow",
      overallStatus: "Yellow",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
      projectUpdateNotes:
        "UAT kickoff begins on 09/11. Environment is ready for UAT users, no issues anticipated",
    },
    {
      projectId: "2",
      projectName: "WFDSS",
      programName: "Forest Service",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Green",
      escalationMetricStatus: "Yellow",
      overallStatus: "Yellow",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "3",
      projectName: "PSAS",
      programName: "USDA",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Yellow",
      escalationMetricStatus: "Green",
      overallStatus: "Green",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "4",
      projectName: "SUDS",
      programName: "Forest Service",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Red",
      overallStatus: "Red",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "5",
      projectName: "ACWS Example #1",
      programName: "ACWS",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Yellow",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Red",
      overallStatus: "Red",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "6",
      projectName: "CON-IT Example #1",
      programName: "CON-IT",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Red",
      overallStatus: "Red",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
  
    {
      projectId: "7",
      projectName: "CONEXUS Example #1",
      programName: "GSA CONEXUS",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Red",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Yellow",
      overallStatus: "Green",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "8",
      projectName: "NSOBS Example #1",
      programName: "GSA NSOBS",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Yellow",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Yellow",
      overallStatus: "Green",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "9",
      projectName: "VMDI",
      programName: "Infrastructure",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Red",
      overallStatus: "Red",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "10",
      projectName: "Jira",
      programName: "Infrastructure",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Red",
      overallStatus: "Red",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "11",
      projectName: "Bamboo",
      programName: "Infrastructure",
      agileMetricStatus: "Yellow",
      staffingMetricStatus: "Yellow",
      modernizationMetricStatus: "Green",
      escalationMetricStatus: "Yellow",
      overallStatus: "Yellow",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "12",
      projectName: "BitBucket",
      programName: "Infrastructure",
      agileMetricStatus: "Red",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Green",
      escalationMetricStatus: "Red",
      overallStatus: "Red",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "13",
      projectName: "Example Infra project",
      programName: "Infrastructure",
      agileMetricStatus: "Red",
      staffingMetricStatus: "Green",
      modernizationMetricStatus: "Green",
      escalationMetricStatus: "Red",
      overallStatus: "Green",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
    {
      projectId: "14",
      projectName: "ACWS Example #2",
      programName: "ACWS",
      agileMetricStatus: "Green",
      staffingMetricStatus: "Yellow",
      modernizationMetricStatus: "Red",
      escalationMetricStatus: "Red",
      overallStatus: "Red",
      dateOfLastMetricStatusUpdate: new Date(),
      contact: "no-reply@usda.gov",
    },
  ];